# Generated by Django 5.0.14 on 2026-06-11 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpick_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_expense', models.PositiveIntegerField(blank=True, null=True)),
                ('residence_type', models.CharField(blank=True, max_length=50)),
                ('saving_status', models.CharField(blank=True, max_length=50)),
                ('invest_experience', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
