# Generated by Django 5.0.14 on 2026-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpick_app', '0013_userfavoritestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFinancialTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_date', models.DateField(unique=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tip_date'],
            },
        ),
    ]
