# Generated by Django 5.0.14 on 2026-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpick_app', '0014_dailyfinancialtip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateField()),
                ('financial_type', models.CharField(max_length=50)),
                ('deposit_product_ids', models.JSONField(blank=True, default=list)),
                ('stock_codes', models.JSONField(blank=True, default=list)),
                ('stock_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recommendation_date', 'financial_type'],
                'unique_together': {('recommendation_date', 'financial_type')},
            },
        ),
    ]
