# Generated by Django 5.0.14 on 2026-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpick_app', '0015_aiproductrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
