# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpick_app', '0016_userprofile_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='profile_images/'),
        ),
    ]
