# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpick_app', '0017_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeywordTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched_at'],
            },
        ),
    ]
